# ============================================================
# data.py — AI Tools Database
# All 53 AI tools stored as a Python list of dictionaries.
#
# INTERVIEW TIP: This is a "data layer" — we keep data separate
# from logic (app.py) and presentation (templates/).
# This makes the code easier to maintain and test.
# ============================================================

tools = [

    # ── WRITING (9 tools) ──────────────────────────────────────
    {
        "id": 1,
        "name": "ChatGPT",
        "category": "Writing",
        "description": "OpenAI's flagship AI chatbot for conversation, writing, coding, and analysis. The most widely used AI assistant with over 100 million users worldwide.",
        "logo": "🤖",
        "color": "#10a37f",
        "website": "https://chatgpt.com",
        "trending": True,
    },
    {
        "id": 2,
        "name": "Claude",
        "category": "Writing",
        "description": "Anthropic's AI assistant known for thoughtful, nuanced responses and long-context understanding. Excels at writing, analysis, and research with a focus on safety.",
        "logo": "🧠",
        "color": "#CC785C",
        "website": "https://claude.ai",
        "trending": True,
    },
    {
        "id": 3,
        "name": "Gemini",
        "category": "Writing",
        "description": "Google's multimodal AI model integrated with Google Workspace. Handles text, images, and documents — ideal for writing, research, and productivity.",
        "logo": "✨",
        "color": "#4285F4",
        "website": "https://gemini.google.com",
        "trending": True,
    },
    {
        "id": 4,
        "name": "Jasper",
        "category": "Writing",
        "description": "Enterprise AI writing platform for marketing teams. Generate blog posts, ads, emails, and long-form content at scale with brand voice consistency.",
        "logo": "🦊",
        "color": "#FF7A45",
        "website": "https://www.jasper.ai",
        "trending": False,
    },
    {
        "id": 5,
        "name": "Copy.ai",
        "category": "Writing",
        "description": "AI-powered copywriting tool that helps marketers create compelling content, ad copy, and product descriptions in seconds.",
        "logo": "✏️",
        "color": "#7C3AED",
        "website": "https://www.copy.ai",
        "trending": False,
    },
    {
        "id": 6,
        "name": "Writesonic",
        "category": "Writing",
        "description": "AI writing platform for SEO-optimized articles, ads, and social content. Features Chatsonic — a ChatGPT alternative with real-time web access.",
        "logo": "📄",
        "color": "#06B6D4",
        "website": "https://writesonic.com",
        "trending": False,
    },
    {
        "id": 7,
        "name": "Rytr",
        "category": "Writing",
        "description": "Affordable AI writing assistant that creates high-quality content for blogs, emails, and social media in 30+ languages with 40+ use case templates.",
        "logo": "🖊️",
        "color": "#8B5CF6",
        "website": "https://rytr.me",
        "trending": False,
    },
    {
        "id": 8,
        "name": "Grammarly",
        "category": "Writing",
        "description": "AI-powered writing assistant that checks grammar, spelling, clarity, and tone across all writing platforms — from emails to documents.",
        "logo": "📖",
        "color": "#15C39A",
        "website": "https://www.grammarly.com",
        "trending": False,
    },
    {
        "id": 9,
        "name": "Character.ai",
        "category": "Writing",
        "description": "AI platform for creating and chatting with custom AI characters. Talk to AI personas of historical figures or fictional characters.",
        "logo": "🎭",
        "color": "#2563EB",
        "website": "https://character.ai",
        "trending": False,
    },

    # ── CODING (6 tools) ───────────────────────────────────────
    {
        "id": 10,
        "name": "GitHub Copilot",
        "category": "Coding",
        "description": "AI pair programmer by GitHub and OpenAI that suggests code completions and writes functions in real-time inside VS Code, JetBrains, and more.",
        "logo": "🐙",
        "color": "#6E5494",
        "website": "https://github.com/features/copilot",
        "trending": False,
    },
    {
        "id": 11,
        "name": "Cursor",
        "category": "Coding",
        "description": "AI-first code editor built on VS Code. Write, edit, and debug with natural language. Understands your entire codebase for context-aware suggestions.",
        "logo": "⬛",
        "color": "#0066FF",
        "website": "https://www.cursor.com",
        "trending": False,
    },
    {
        "id": 12,
        "name": "Replit",
        "category": "Coding",
        "description": "Online IDE with AI assistance. Write, run, and deploy code in any language from the browser. Great for beginners and rapid prototyping.",
        "logo": "🔧",
        "color": "#F26207",
        "website": "https://replit.com",
        "trending": False,
    },
    {
        "id": 13,
        "name": "Tabnine",
        "category": "Coding",
        "description": "Privacy-first AI code completion that learns from your codebase. Suggests whole lines and functions, supports 30+ languages, can run locally.",
        "logo": "⌨️",
        "color": "#CA4CF6",
        "website": "https://www.tabnine.com",
        "trending": False,
    },
    {
        "id": 14,
        "name": "Amazon Q Dev",
        "category": "Coding",
        "description": "AWS's AI coding assistant (formerly CodeWhisperer) for generating, debugging, and optimizing code with deep integration with AWS services.",
        "logo": "☁️",
        "color": "#FF9900",
        "website": "https://aws.amazon.com/q/developer/",
        "trending": False,
    },
    {
        "id": 15,
        "name": "Windsurf",
        "category": "Coding",
        "description": "Agentic AI code editor by Codeium featuring Cascade — an AI agent that autonomously completes multi-step coding tasks with full codebase awareness.",
        "logo": "🏄",
        "color": "#00C9A7",
        "website": "https://windsurf.com",
        "trending": False,
    },

    # ── IMAGE GENERATION (7 tools) ─────────────────────────────
    {
        "id": 16,
        "name": "Midjourney",
        "category": "Image Generation",
        "description": "The leading AI image generator for breathtaking artistic visuals. Used by designers, filmmakers, and artists worldwide to create stunning images from text.",
        "logo": "🌈",
        "color": "#2D3561",
        "website": "https://www.midjourney.com",
        "trending": True,
    },
    {
        "id": 17,
        "name": "DALL-E 3",
        "category": "Image Generation",
        "description": "OpenAI's image generation model with precise prompt following and photorealistic output. Integrated directly into ChatGPT for easy access.",
        "logo": "🖼️",
        "color": "#10a37f",
        "website": "https://openai.com/dall-e-3",
        "trending": False,
    },
    {
        "id": 18,
        "name": "Stable Diffusion",
        "category": "Image Generation",
        "description": "Open-source AI image generator by Stability AI. Highly customizable with thousands of community models and plugins. Run locally or in the cloud.",
        "logo": "🎭",
        "color": "#7C3AED",
        "website": "https://stability.ai",
        "trending": False,
    },
    {
        "id": 19,
        "name": "Leonardo AI",
        "category": "Image Generation",
        "description": "Production-ready AI image platform for game developers, artists, and creators. Features fine-tuned style models, image-to-image generation, and a robust API.",
        "logo": "🦁",
        "color": "#E8B86D",
        "website": "https://leonardo.ai",
        "trending": False,
    },
    {
        "id": 20,
        "name": "Adobe Firefly",
        "category": "Image Generation",
        "description": "Adobe's commercial-safe generative AI model trained on licensed images. Integrated with Photoshop, Illustrator, and the full Creative Cloud suite.",
        "logo": "🦋",
        "color": "#FF0000",
        "website": "https://firefly.adobe.com",
        "trending": False,
    },
    {
        "id": 21,
        "name": "Ideogram",
        "category": "Image Generation",
        "description": "AI image generator with exceptional text rendering capabilities — the best for embedding readable text inside images. Perfect for logos and posters.",
        "logo": "💡",
        "color": "#6366F1",
        "website": "https://ideogram.ai",
        "trending": False,
    },
    {
        "id": 22,
        "name": "Flux",
        "category": "Image Generation",
        "description": "State-of-the-art image generation models by Black Forest Labs. FLUX.1 delivers exceptional photorealism and precise prompt accuracy.",
        "logo": "⚡",
        "color": "#4B5563",
        "website": "https://blackforestlabs.ai",
        "trending": False,
    },

    # ── VIDEO GENERATION (7 tools) ─────────────────────────────
    {
        "id": 23,
        "name": "Runway",
        "category": "Video Generation",
        "description": "Professional AI video generation and editing platform used by filmmakers and studios. Gen-3 Alpha produces cinema-quality video from text and images.",
        "logo": "🛫",
        "color": "#374151",
        "website": "https://runwayml.com",
        "trending": False,
    },
    {
        "id": 24,
        "name": "Pika",
        "category": "Video Generation",
        "description": "AI video generation that creates high-quality, expressive videos from text prompts and images. Known for creative control and smooth animations.",
        "logo": "✴️",
        "color": "#FF6B35",
        "website": "https://pika.art",
        "trending": False,
    },
    {
        "id": 25,
        "name": "Synthesia",
        "category": "Video Generation",
        "description": "AI video platform with 230+ realistic AI avatars in 130+ languages. Create professional training and marketing videos without a camera or studio.",
        "logo": "🎥",
        "color": "#5B4FE9",
        "website": "https://www.synthesia.io",
        "trending": False,
    },
    {
        "id": 26,
        "name": "HeyGen",
        "category": "Video Generation",
        "description": "Create AI avatar videos for marketing and training. Clone your voice and avatar, or choose from 100+ built-in AI presenters in minutes.",
        "logo": "🎬",
        "color": "#FF6C2F",
        "website": "https://www.heygen.com",
        "trending": False,
    },
    {
        "id": 27,
        "name": "Luma AI",
        "category": "Video Generation",
        "description": "Dream Machine by Luma generates high-quality, realistic videos from text and images with fluid motion, accurate physics, and cinematic quality.",
        "logo": "🔮",
        "color": "#6B21A8",
        "website": "https://lumalabs.ai",
        "trending": False,
    },
    {
        "id": 28,
        "name": "Kling AI",
        "category": "Video Generation",
        "description": "Kuaishou's powerful AI video model producing cinematic quality 2-minute videos with realistic physics simulation and precise motion control.",
        "logo": "🎞️",
        "color": "#1E40AF",
        "website": "https://klingai.com",
        "trending": False,
    },
    {
        "id": 29,
        "name": "Sora",
        "category": "Video Generation",
        "description": "OpenAI's text-to-video model that generates realistic and imaginative scenes from text instructions with remarkable consistency and detail.",
        "logo": "🌀",
        "color": "#10a37f",
        "website": "https://sora.com",
        "trending": False,
    },

    # ── PRODUCTIVITY (7 tools) ─────────────────────────────────
    {
        "id": 30,
        "name": "Notion AI",
        "category": "Productivity",
        "description": "AI built into Notion that helps you write, summarize, brainstorm, translate, and manage tasks — all within your team's workspace and knowledge base.",
        "logo": "📋",
        "color": "#3D3D3D",
        "website": "https://www.notion.so",
        "trending": False,
    },
    {
        "id": 31,
        "name": "Zapier",
        "category": "Productivity",
        "description": "No-code automation platform with AI that connects 7,000+ apps and automates workflows. Use natural language to describe automations you want to build.",
        "logo": "⚡",
        "color": "#FF4A00",
        "website": "https://zapier.com",
        "trending": False,
    },
    {
        "id": 32,
        "name": "Otter.ai",
        "category": "Productivity",
        "description": "AI meeting assistant that records, transcribes, summarizes, and generates action items from your Zoom, Teams, or Google Meet calls automatically.",
        "logo": "🎙️",
        "color": "#00A3BF",
        "website": "https://otter.ai",
        "trending": False,
    },
    {
        "id": 33,
        "name": "Mem.ai",
        "category": "Productivity",
        "description": "AI-powered note-taking app that automatically organizes your notes and surfaces the most relevant information when you need it — no folders required.",
        "logo": "🧠",
        "color": "#8B5CF6",
        "website": "https://mem.ai",
        "trending": False,
    },
    {
        "id": 34,
        "name": "Reclaim AI",
        "category": "Productivity",
        "description": "AI scheduling assistant that automatically finds the best time for tasks, habits, and meetings in Google Calendar — protecting your focus time intelligently.",
        "logo": "📅",
        "color": "#6366F1",
        "website": "https://reclaim.ai",
        "trending": False,
    },
    {
        "id": 35,
        "name": "Taskade",
        "category": "Productivity",
        "description": "AI-powered project management and collaboration platform. Build custom AI agents for your team that can research, write, and execute tasks autonomously.",
        "logo": "✅",
        "color": "#7C3AED",
        "website": "https://www.taskade.com",
        "trending": False,
    },
    {
        "id": 36,
        "name": "ElevenLabs",
        "category": "Productivity",
        "description": "Best-in-class AI voice synthesis for ultra-realistic text-to-speech, instant voice cloning, and multilingual dubbing. Used by creators and enterprises.",
        "logo": "🎵",
        "color": "#1DB954",
        "website": "https://elevenlabs.io",
        "trending": False,
    },

    # ── RESEARCH (6 tools) ─────────────────────────────────────
    {
        "id": 37,
        "name": "Perplexity",
        "category": "Research",
        "description": "AI-powered search engine that provides direct answers with real-time web search and cited sources. The best AI for research that needs up-to-date information.",
        "logo": "🔍",
        "color": "#20808D",
        "website": "https://www.perplexity.ai",
        "trending": False,
    },
    {
        "id": 38,
        "name": "Elicit",
        "category": "Research",
        "description": "AI research assistant that automates literature review. Find relevant papers, extract key data, and synthesize findings from millions of academic sources.",
        "logo": "📊",
        "color": "#4F46E5",
        "website": "https://elicit.com",
        "trending": False,
    },
    {
        "id": 39,
        "name": "Consensus",
        "category": "Research",
        "description": "AI-powered search engine for scientific research. Get evidence-based answers and synthesized insights from peer-reviewed papers with citations.",
        "logo": "📈",
        "color": "#0EA5E9",
        "website": "https://consensus.app",
        "trending": False,
    },
    {
        "id": 40,
        "name": "Semantic Scholar",
        "category": "Research",
        "description": "Free AI-powered research tool by the Allen Institute for AI. Search 200M+ academic papers with semantic understanding and citation graph exploration.",
        "logo": "📚",
        "color": "#1B4FD8",
        "website": "https://www.semanticscholar.org",
        "trending": False,
    },
    {
        "id": 41,
        "name": "SciSpace",
        "category": "Research",
        "description": "AI tool for reading and understanding research papers. Get plain-English explanations, summaries, and ask questions about any paper.",
        "logo": "🔭",
        "color": "#7C3AED",
        "website": "https://scispace.com",
        "trending": False,
    },
    {
        "id": 42,
        "name": "You.com",
        "category": "Research",
        "description": "AI search engine with a research mode that cites sources, summarizes web content, and allows multi-turn conversational follow-up on any topic.",
        "logo": "🌐",
        "color": "#E53E3E",
        "website": "https://you.com",
        "trending": False,
    },

    # ── MARKETING (5 tools) ────────────────────────────────────
    {
        "id": 43,
        "name": "Canva AI",
        "category": "Marketing",
        "description": "Design platform supercharged with AI — generate images, rewrite text, animate designs, and create entire social media campaigns with Magic Studio.",
        "logo": "🎨",
        "color": "#00C4CC",
        "website": "https://www.canva.com",
        "trending": True,
    },
    {
        "id": 44,
        "name": "AdCreative.ai",
        "category": "Marketing",
        "description": "AI platform for generating high-converting ad creatives, banners, and social media content at scale. Integrates with Facebook, Google, and LinkedIn Ads.",
        "logo": "📣",
        "color": "#6366F1",
        "website": "https://www.adcreative.ai",
        "trending": False,
    },
    {
        "id": 45,
        "name": "Surfer SEO",
        "category": "Marketing",
        "description": "AI-powered SEO tool that analyzes top-ranking content and guides you to write content that ranks on Google with a real-time content editor.",
        "logo": "🏄",
        "color": "#F59E0B",
        "website": "https://surferseo.com",
        "trending": False,
    },
    {
        "id": 46,
        "name": "Pictory",
        "category": "Marketing",
        "description": "AI video creation tool that converts blog posts, scripts, and articles into engaging short videos for social media with automatic captions and voiceover.",
        "logo": "🎬",
        "color": "#7C3AED",
        "website": "https://pictory.ai",
        "trending": False,
    },
    {
        "id": 47,
        "name": "Brandmark",
        "category": "Marketing",
        "description": "AI logo and brand identity generator that creates unique, professional logos from just your brand name and style preferences — in seconds.",
        "logo": "🏷️",
        "color": "#F59E0B",
        "website": "https://brandmark.io",
        "trending": False,
    },

    # ── EDUCATION (6 tools) ────────────────────────────────────
    {
        "id": 48,
        "name": "Khan Academy AI",
        "category": "Education",
        "description": "Khanmigo — Khan Academy's AI tutor that guides students through problems with Socratic questioning and provides personalized learning support.",
        "logo": "🎓",
        "color": "#14BF96",
        "website": "https://www.khanacademy.org",
        "trending": False,
    },
    {
        "id": 49,
        "name": "Duolingo AI",
        "category": "Education",
        "description": "Duolingo uses AI to personalize language lessons, adapt difficulty to your skill, and power Max features like AI roleplay conversations.",
        "logo": "🦉",
        "color": "#58CC02",
        "website": "https://www.duolingo.com",
        "trending": False,
    },
    {
        "id": 50,
        "name": "Quizlet AI",
        "category": "Education",
        "description": "AI-enhanced study platform that auto-generates flashcards, practice tests, and study plans from your notes. Q-Chat is an AI tutor built right in.",
        "logo": "📝",
        "color": "#4257B2",
        "website": "https://quizlet.com",
        "trending": False,
    },
    {
        "id": 51,
        "name": "Photomath",
        "category": "Education",
        "description": "AI math solver that scans handwritten or printed problems and provides step-by-step solutions with visual explanations — from arithmetic to calculus.",
        "logo": "📐",
        "color": "#4CAF50",
        "website": "https://photomath.com",
        "trending": False,
    },
    {
        "id": 52,
        "name": "Socratic",
        "category": "Education",
        "description": "Google's AI learning app — take a photo of any homework question and get step-by-step explanations, visual breakdowns, and curated learning resources.",
        "logo": "📱",
        "color": "#4285F4",
        "website": "https://socratic.org",
        "trending": False,
    },
    {
        "id": 53,
        "name": "Coursera AI",
        "category": "Education",
        "description": "Coursera's AI tools help you learn faster with personalized course recommendations, AI-generated practice exercises, and an AI coach for guided support.",
        "logo": "🏫",
        "color": "#0056D2",
        "website": "https://www.coursera.org",
        "trending": False,
    },

]
